aws:
  profile: prod
  region: ap-northeast-2

dms:
  output_dir: dms-config
  parsed_output_file: dms-config.xlsx

rules:
  output_dir: dms_rules
  tables:
    # - db.schema.table
  except_tables:
    # - db.schema.table
  except_columns:
    # - db.schema.table.column
  lower_case_tables:
    # - db.schema.table
